### ISSUE TITLE
Not enough 🗿

### ISSUE THREAD

**Issue by squidink7** [Barry-B-Benson6/Learning-Feedback-student#1]
Let me start off by saying this is an excellent app, I've been using it for years to manage my taxes and teach my children linear algebra, however it has recently dawned on me the lack of 🗿 in this program. This is simply unacceptable. Any modern self-respecting application needs to be at least 20% 🗿 in order to be taken seriously in the industry. I strongly urge you to reconsider this, and add some more 🗿 to your app, before its too late.

**Comment by Barry-B-Benson6** [comment]
Is that a threat?

**Comment by squidink7** [comment]
Yes.

**Comment by Barry-B-Benson6** [comment]
I'm not scared of you
